-- MySQL Script generated by MySQL Workbench
-- Mon Jul 11 23:30:15 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema bdreportes
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `bdreportes` ;

-- -----------------------------------------------------
-- Schema bdreportes
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bdreportes` DEFAULT CHARACTER SET utf8 ;
USE `bdreportes` ;

-- -----------------------------------------------------
-- Table `bdreportes`.`Departamento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bdreportes`.`Departamento` ;

CREATE TABLE IF NOT EXISTS `bdreportes`.`Departamento` (
  `idDepartamento` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(50) NOT NULL,
  `planta` INT NOT NULL,
  PRIMARY KEY (`idDepartamento`),
  UNIQUE INDEX `nombre_UNIQUE` (`nombre` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdreportes`.`Categoria`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bdreportes`.`Categoria` ;

CREATE TABLE IF NOT EXISTS `bdreportes`.`Categoria` (
  `idCategoria` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(20) NOT NULL,
  `tipo` INT NOT NULL,
  PRIMARY KEY (`idCategoria`),
  UNIQUE INDEX `nombre_UNIQUE` (`nombre` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdreportes`.`Usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bdreportes`.`Usuario` ;

CREATE TABLE IF NOT EXISTS `bdreportes`.`Usuario` (
  `username` VARCHAR(20) NOT NULL,
  `password` VARCHAR(30) NOT NULL,
  `nombre` VARCHAR(30) NOT NULL,
  `apellidoPaterno` VARCHAR(30) NOT NULL,
  `apellidoMaterno` VARCHAR(30) NOT NULL,
  `categoria` INT NOT NULL,
  `departamento` INT NOT NULL,
  PRIMARY KEY (`username`),
  INDEX `fk_Usuario_Departamento_idx` (`departamento` ASC) VISIBLE,
  INDEX `fk_Usuario_Categoria1_idx` (`categoria` ASC) VISIBLE,
  CONSTRAINT `fk_Usuario_Departamento`
    FOREIGN KEY (`departamento`)
    REFERENCES `bdreportes`.`Departamento` (`idDepartamento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Usuario_Categoria1`
    FOREIGN KEY (`categoria`)
    REFERENCES `bdreportes`.`Categoria` (`idCategoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdreportes`.`Tipo_reporte`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bdreportes`.`Tipo_reporte` ;

CREATE TABLE IF NOT EXISTS `bdreportes`.`Tipo_reporte` (
  `idTipo` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NOT NULL,
  `prioridad` INT NOT NULL,
  PRIMARY KEY (`idTipo`),
  UNIQUE INDEX `nombre_UNIQUE` (`nombre` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdreportes`.`Estado`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bdreportes`.`Estado` ;

CREATE TABLE IF NOT EXISTS `bdreportes`.`Estado` (
  `idEstado` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`idEstado`),
  UNIQUE INDEX `nombre_UNIQUE` (`nombre` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdreportes`.`Reporte`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bdreportes`.`Reporte` ;

CREATE TABLE IF NOT EXISTS `bdreportes`.`Reporte` (
  `folio` INT NOT NULL AUTO_INCREMENT,
  `fecha_reporte` VARCHAR(45) NOT NULL,
  `descripcion` VARCHAR(280) NOT NULL,
  `usuario_reporta` VARCHAR(20) NOT NULL,
  `tipo` INT NOT NULL,
  `estado` INT NOT NULL DEFAULT 1,
  `fecha_respuesta` VARCHAR(45) NULL,
  `respuesta` VARCHAR(280) NULL,
  `usuario_responde` VARCHAR(20) NOT NULL DEFAULT 'root',
  PRIMARY KEY (`folio`, `usuario_reporta`),
  INDEX `fk_Reporte_Tipo_reporte1_idx` (`tipo` ASC) VISIBLE,
  INDEX `fk_Reporte_Estado1_idx` (`estado` ASC) VISIBLE,
  INDEX `fk_Reporte_Usuario1_idx` (`usuario_reporta` ASC) VISIBLE,
  INDEX `fk_Reporte_Usuario2_idx` (`usuario_responde` ASC) VISIBLE,
  CONSTRAINT `fk_Reporte_Tipo_reporte1`
    FOREIGN KEY (`tipo`)
    REFERENCES `bdreportes`.`Tipo_reporte` (`idTipo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Reporte_Estado1`
    FOREIGN KEY (`estado`)
    REFERENCES `bdreportes`.`Estado` (`idEstado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Reporte_Usuario1`
    FOREIGN KEY (`usuario_reporta`)
    REFERENCES `bdreportes`.`Usuario` (`username`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Reporte_Usuario2`
    FOREIGN KEY (`usuario_responde`)
    REFERENCES `bdreportes`.`Usuario` (`username`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `bdreportes`.`Departamento`
-- -----------------------------------------------------
START TRANSACTION;
USE `bdreportes`;
INSERT INTO `bdreportes`.`Departamento` (`idDepartamento`, `nombre`, `planta`) VALUES (1, 'Ejemplo', 0);
INSERT INTO `bdreportes`.`Departamento` (`idDepartamento`, `nombre`, `planta`) VALUES (2, 'Fomento Sanitario', 3);
INSERT INTO `bdreportes`.`Departamento` (`idDepartamento`, `nombre`, `planta`) VALUES (3, 'Evidencia y manejo de riesgos', 3);
INSERT INTO `bdreportes`.`Departamento` (`idDepartamento`, `nombre`, `planta`) VALUES (4, 'Resoluciones', 1);
INSERT INTO `bdreportes`.`Departamento` (`idDepartamento`, `nombre`, `planta`) VALUES (5, 'Dictamen', 1);
INSERT INTO `bdreportes`.`Departamento` (`idDepartamento`, `nombre`, `planta`) VALUES (6, 'Autorizaciones', -1);
INSERT INTO `bdreportes`.`Departamento` (`idDepartamento`, `nombre`, `planta`) VALUES (7, 'Operación sanitaria', 0);
INSERT INTO `bdreportes`.`Departamento` (`idDepartamento`, `nombre`, `planta`) VALUES (8, 'Dirección', 1);
INSERT INTO `bdreportes`.`Departamento` (`idDepartamento`, `nombre`, `planta`) VALUES (9, 'Emergencias', -1);
INSERT INTO `bdreportes`.`Departamento` (`idDepartamento`, `nombre`, `planta`) VALUES (10, 'Administración', 2);
INSERT INTO `bdreportes`.`Departamento` (`idDepartamento`, `nombre`, `planta`) VALUES (11, 'Subdirección control sanitario', 1);
INSERT INTO `bdreportes`.`Departamento` (`idDepartamento`, `nombre`, `planta`) VALUES (12, 'Subdirección de salud ambiental', 1);
INSERT INTO `bdreportes`.`Departamento` (`idDepartamento`, `nombre`, `planta`) VALUES (13, 'Coordinación de informática', 2);

COMMIT;


-- -----------------------------------------------------
-- Data for table `bdreportes`.`Categoria`
-- -----------------------------------------------------
START TRANSACTION;
USE `bdreportes`;
INSERT INTO `bdreportes`.`Categoria` (`idCategoria`, `nombre`, `tipo`) VALUES (1, 'Administrador', 1);
INSERT INTO `bdreportes`.`Categoria` (`idCategoria`, `nombre`, `tipo`) VALUES (2, 'Soporte', 2);
INSERT INTO `bdreportes`.`Categoria` (`idCategoria`, `nombre`, `tipo`) VALUES (3, 'Director', 3);
INSERT INTO `bdreportes`.`Categoria` (`idCategoria`, `nombre`, `tipo`) VALUES (4, 'Subdirector', 3);
INSERT INTO `bdreportes`.`Categoria` (`idCategoria`, `nombre`, `tipo`) VALUES (5, 'Jefe de departamento', 3);
INSERT INTO `bdreportes`.`Categoria` (`idCategoria`, `nombre`, `tipo`) VALUES (6, 'Secretaria', 3);
INSERT INTO `bdreportes`.`Categoria` (`idCategoria`, `nombre`, `tipo`) VALUES (7, 'General', 3);

COMMIT;


-- -----------------------------------------------------
-- Data for table `bdreportes`.`Usuario`
-- -----------------------------------------------------
START TRANSACTION;
USE `bdreportes`;
INSERT INTO `bdreportes`.`Usuario` (`username`, `password`, `nombre`, `apellidoPaterno`, `apellidoMaterno`, `categoria`, `departamento`) VALUES ('root', 'root', 'Usuario raíz', 'prueba', 'prueba', 1, 1);
INSERT INTO `bdreportes`.`Usuario` (`username`, `password`, `nombre`, `apellidoPaterno`, `apellidoMaterno`, `categoria`, `departamento`) VALUES ('admin', 'admin', 'Administrador', 'Coordinacion', 'Informatica', 1, 1);
INSERT INTO `bdreportes`.`Usuario` (`username`, `password`, `nombre`, `apellidoPaterno`, `apellidoMaterno`, `categoria`, `departamento`) VALUES ('soporte', 'soporte', 'Usuario', 'soporte', 'informatico', 2, 1);
INSERT INTO `bdreportes`.`Usuario` (`username`, `password`, `nombre`, `apellidoPaterno`, `apellidoMaterno`, `categoria`, `departamento`) VALUES ('user', 'user', 'General', 'Apellido', 'de ejemplo', 3, 1);

COMMIT;


-- -----------------------------------------------------
-- Data for table `bdreportes`.`Tipo_reporte`
-- -----------------------------------------------------
START TRANSACTION;
USE `bdreportes`;
INSERT INTO `bdreportes`.`Tipo_reporte` (`idTipo`, `nombre`, `prioridad`) VALUES (1, 'Otro', 10);

COMMIT;


-- -----------------------------------------------------
-- Data for table `bdreportes`.`Estado`
-- -----------------------------------------------------
START TRANSACTION;
USE `bdreportes`;
INSERT INTO `bdreportes`.`Estado` (`idEstado`, `nombre`) VALUES (1, 'Espera');
INSERT INTO `bdreportes`.`Estado` (`idEstado`, `nombre`) VALUES (2, 'Atención');
INSERT INTO `bdreportes`.`Estado` (`idEstado`, `nombre`) VALUES (3, 'Finalizado');
INSERT INTO `bdreportes`.`Estado` (`idEstado`, `nombre`) VALUES (4, 'Cancelado');

COMMIT;

